#!/bin/sh

source ./functions.sh

# Mount the /dev, /proc and /sys filesystems.
mount -t devtmpfs none /dev
if [ $? -ne 0 ]; then
    echo "Unable to mount /dev"
    die
fi
mount -t proc none /proc
if [ $? -ne 0 ]; then
    echo "Unable to mount /proc"
    die
fi
mount -t sysfs none /sys
if [ $? -ne 0 ]; then
    echo "Unable to mount /sys"
    die
fi

# Setup network
ip link set eth0 up
if [ $? -ne 0 ]; then
    echo "Unable to bring up network device eth0"
    panic
fi

udhcpc -n
if [ $? -ne 0 ]; then
    echo "DHCP client error"
    panic
fi

echo "
     /@@
     @     @@@@@
     ,@@.@@@@@
       @
      @
      @
       @# ,@@@@@@@
       @@
     @@
   @@
  @@
  @@
  @@
   @@@.
    @@@@@@@@@@@@@@%
       @@@@@@@@@@@@&
                  @@
                  @@
                 %@
           @@@@@@&
"
uname -a
echo "This script just starts a shell, TODO: actual init"

# go interactive
panic
