#!/bin/sh

# Mount the /dev, /proc and /sys filesystems.
mount -t devtmpfs none /dev
mount -t proc none /proc
mount -t sysfs none /sys

echo "
     /@@
     @     @@@@@
     ,@@.@@@@@
       @
      @
      @
       @# ,@@@@@@@
       @@
     @@
   @@
  @@
  @@
  @@
   @@@.
    @@@@@@@@@@@@@@%
       @@@@@@@@@@@@&
                  @@
                  @@
                 %@
           @@@@@@&
"
uname -a
echo "This script just starts a shell, TODO: actual init"

# go interactive
setsid cttyhack sh

# Power off
echo o > /proc/sysrq-trigger
